### ISSUE TITLE
Babel 6?

### ISSUE THREAD

**Issue by chrisfls** [jussi-kalliokoski/babel-plugin-operator-overload#1]
Can we get this working on babel 6?

**Comment by jussi-kalliokoski** [comment]
@kress95 just published v2.0.0 to npm with babel 6 support. If you could report back with whether it works for you, would be great! :star2:

**Comment by chrisfls** [comment]
Just tested it here, no problems so far.

**Comment by jussi-kalliokoski** [comment]
@kress95 Great! Thanks! :100:
